name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  DOTNET_VERSION: '8.0'                 # set this to the .NET Core version to use

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Build with dotnet
        run: dotnet build --configuration Release